import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
import Wrapper from '@/components/wrapper/Wrapper';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        
        <Wrapper>
        {children}
          
          </Wrapper>   
         
        </body>
    </html>
  )
}
